#!/bin/bash
#PBS -l nodes=1:ppn=1,walltime=0:30:00
#PBS -N app-slicer-midsagittal

# create images
echo "creating images of dwi volumes with slicer"
time singularity exec -e docker://brainlife/fsl:5.0.9 ./run.sh

# creat gif
echo "creating gif with imagemagick"
time singularity exec -e docker://dpokidov/imagemagick convert -delay 30 -loop 1 ./raw/*.png ./raw/out.gif

if [ ! -f ./raw/out.gif ]; then
	echo "something failed. check logs and derivatives"
	exit 1
else
	echo "complete"
	cp ./raw/vol0000.png ./raw/out.png
	exit 0
fi
